spring:
  application:
    name: {{ cookiecutter.service_slug }}
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: "readinessState"
  metrics:
    export:
      statsd:
        enabled: true
        flavor: datadog
        host: datadog-agent #kubernetes service instance
      datadog:
        enabled: true
    tags:
      application: "{{ cookiecutter.application_tag }}"
      env: ${spring.profiles.active}
      domain: "{{ cookiecutter.domain_tag }}"
      service: "{{ cookiecutter.service_tag }}"
logging:
  level:
    root: INFO
    com.{{ cookiecutter.service_namespace }}: DEBUG
