spring:
  application:
    name: {{ cookiecutter.service_slug }}
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: "readinessState"
logging:
  level:
    root: INFO
    com.{{ cookiecutter.service_namespace }}: DEBUG
