name: Main Branch Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: {%raw%}ci-tests-${{ github.ref }}-1{%endraw%}
  cancel-in-progress: true

jobs:
  call-get-version:
    uses: bullyrooks/service-workflow/.github/workflows/get-version.yaml@main
    secrets:
      GH_TOKEN: {%raw%}${{ secrets.CHART_TOKEN }}{%endraw%}

  call-compile:
    uses: bullyrooks/service-workflow/.github/workflows/compile.yaml@main

  call-build-image-with-push:
    needs:
      - call-get-version
    uses: bullyrooks/service-workflow/.github/workflows/build-image-with-push.yaml@main
    with:
      version: {%raw%}${{ needs.call-get-version.outputs.version }}{%endraw%}
      image-name: {{ cookiecutter.service_registry }}
    secrets:
      canister-username: {%raw%}${{ secrets.CANISTER_USERNAME }}{%endraw%}
      canister-password: {%raw%}${{ secrets.CANISTER_PASSWORD }}{%endraw%}

  call-helm-chart:
    needs:
      - call-get-version
      - call-build-image-with-push
    uses: bullyrooks/service-workflow/.github/workflows/helm-chart.yaml@main
    secrets:
      access-token: {%raw%}${{ secrets.CHART_TOKEN }}{%endraw%}
    with:
      version: {%raw%}${{ needs.call-get-version.outputs.version }}{%endraw%}
